module.exports = [
    { id: 1, 
        title: "Lightning Genome", 
        seller: "Star Labs", 
        condition: "Perfected", 
        price: 15000, 
        totalOffers: 14, 
        image: "/images/lightning-genome.png", 
        description: "Harness the power of the fastest man alive. be fast and stuff yo",
        active: true },
    { id: 2, 
        title: "Regeneration Genome", 
        seller: "Xavier Inc", 
        condition: "Experimental", 
        price: 12500, totalOffers: 8, 
        image: "/images/regeneration-genome.png", 
        description: "For those prone to injury or scared of death, the regeneration genome infuses your DNA with hyper-active repairing agents. Any ailment or injury heals in seconds.",
        active: true },
    { id: 3, 
        title: "Arcane Enhancement Genome", 
        seller: "Warcraft Bioengineering", 
        condition: "Prototype", 
        price: 19250, 
        totalOffers: 20, 
        image: "/images/arcane-genome.png",
        description: "Jealous of those blessed naturally with the ability to channel the arcane? This genome unlocks your mana pool and allows you to cast spells. You still need to learn the spells, though.",
        active: true },
    { id: 4, 
        title: "Waterbreather Genome", 
        seller: "Marvelous Enhancements", 
        condition: "Perfected", 
        price: 12900, 
        totalOffers: 10, 
        image: "/images/waterbreather-genome.png", 
        description: "Like fish? Breathe underwater",
        active: true },
    { id: 5, 
        title: "Colossal Genome", 
        seller: "Xavier Inc", 
        condition: "Dangerous", 
        price: 17000, 
        totalOffers: 3, 
        image: "/images/colossal-genome.png", 
        description: "Ever want to just get hit by a bus and have the bus be the only thing that breaks (lets assume theres no passengers in this bus)? This genome binds to your skin cells to solidify it with the durability like the hardest metals known.",
        active: true },
    { id: 6, 
        title: "Super Soldier Genome", 
        seller: "Marvelous Enhancements", 
        condition: "Untested", 
        price: 24550, 
        totalOffers: 75, 
        image: "/images/super-soldier-genome.png", 
        description: "Just want to be all around a better human? Stronger, faster, prettier, and the endurance of 30 horses? We will not be held liable for any gamma exposure that may/may not transform you into a giant green rage monster.",
        active: true }
  ];
  